### ISSUE TITLE
HTTP proxy settings are applied too late

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-peer-discovery-common#5]
[rabbitmq-users > rabbitmq_peer_discovery_aws behind proxy](https://groups.google.com/d/topic/rabbitmq-users/3vpMkVjimYI/discussion)

rabbitmq/rabbitmq-peer-discovery-aws#6 is keeping me from reproducing the issue on the mailing list. Basically, I think that the `rabbit_peer_discovery_common_app` module is starting after other modules that depend on it, since [this line is what configures proxies](https://github.com/rabbitmq/rabbitmq-peer-discovery-common/blob/master/src/rabbit_peer_discovery_common_app.erl#L23)

**Comment by michaelklishin** [comment]
In the original thread, the OP confirms that AWS peer discovery does work without the proxy settings. Therefore this issue is our working theory. Assuming it affects all HTTP client-based discovery plugins, I'm going to add extra debug logging and try to trace the sequence of operations with Consul or etcd.

**Comment by michaelklishin** [comment]
I have evidence that this is a valid issue. Now we have a chicken-and-egg problem with HTTP client settings: peer discovery happens very early on in boot process, before `rabbitmq-peer-discovery-common` is started. However, we cannot start it that early because it depends on `rabbit` which is in the process of being started. I'm investigating what options we may have.
